steps:
# This step runs the unit tests on the app
- name: 'python:3.7-slim'
  id: CompilePipleline
  entrypoint: /bin/sh
  args:
  - '-c'
  - 'pip install -r requirements.txt --upgrade && python pipeline.py'
#- name: 'gcr.io/cloud-builders/curl'
#  args: ['-F', 'uploadfile=@pipeline.py.tar.gz', '-X', 'POST', 'my-kf-demo.endpoints.kb-poc-262417.cloud.goog/apis/v1beta1/pipelines/upload?name=KFP_DEMO']
